version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout

      - run:
          command: npm install

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run Cypress tests on external website
          command: npx cypress run --config baseUrl=https://app.qa-eclipse.ecapital.com

      - store_artifacts:
          path: cypress/videos
          destination: videos

      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

workflows:
  run-tests:
    jobs:
      - test